---
title: "Bayesian linear regression"
author: "Maria Izabel Cavassim Alves"
date: "`r Sys.Date()`"
output:
  md_document:
    variant: markdown_github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Bayesian linear regresssion (blm)

```blm``` is a R package for fitting linear models in which the statistical analysis were undertaken within the context of Bayesian inference. The ingredients for a regression linear model include the response vector $y= (y_1, y_2, y_3, ..., y_n)$ and a $n$ x $p$ design matrix (e.g. composed of explanatory variables) $X = [x_1, x_2, ..., x_p]$ assumed to have been observed without error. The linear regression model is composed by an intercept ($w_0$), a slope ($w_1 / \beta$) and the error term:

$y_i = w_0 + w_1^Tx_i + ε$, where $ε_i$ is $N(0,\sigma^2)$.

The peculiarities of the Bayesian model compared to the frequentist model is that allow us to give our assumptions, or prior beliefs, about unknown parameters (w) by specifying the prior distribution over those parameters before seeing the data. The way we do it is by treating the weights (w) as random variables coming from a distribution we have partial knowledge about ($p(w|\alpha) = N(0, \alpha^-1I)$). Once we observe the data we can compute the posterior probability distribution for the parameters, given the observed data ($p(w|x,y)$) and the hyper parameters $\alpha$ and $\beta$. (for a bit more details access [here.](https://github.com/izabelcavassim/blm/blob/master/Background.md])

The posterior distribution can be lately used to:

1. Modelling the relationship between x and y.
2. Make predictions for new data points (by integrating over the posterior distribution, see update.blm).
3. Account for uncertainty in the parameters values (see confint.blm).

The features of the package have some similarities to the [lm](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/lm.html) R package. 
The blm package is just available through github and it is under development (version 0.1.0).

## How to install
Open R and then follow the 3 next steps:

.1 You first need to install the devtools package through CRAN.

```{R eval=FALSE}
install.packages("devtools")
```

.2 Load the package just installed. 
```{R eval=FALSE}
library("devtools")
```

.3 And then use the 'install_github' feature to access the blm package
```{R eval=FALSE}
install_github("izabelcavassim/blm")
```

## Functions associted with blm

### The blm model constructor
* ```blm()``` Fits a model, given as a formula, optionally with data provided through the "..." parameter.It takes the model specification in the form of a formula as its parameter model and the prior precision alpha and the “precision” of the data beta. It then computes the mean and the covariance matrix for the model fitted to the data.
*```make_prior()``` Constructs a prior distribution for the weight vectors, which is normally distributed: $\mathrm{N}(\mathbf{0},\,\mathbf{S}_0)$ with
$\mathbf{0}' = (0, 0)$ and $\mathbf{S}_0 = [[1/\alpha, 0], [0, 1/\alpha]]$. And alpha is the hyperparameter or precision
  It returns a prior distribution, with a vector of means and a covariance matrix
*```noresponse_matrix()``` 
*```update()```


### Other functions 
* ```coef()``` Returns the coefficients of the model of class blm().
* ```confint()``` Returns the lower and upper confidence intervals of a parameter (parm) given. The usage of confint is as follow: ```confint(object, parm, level = 0.95, ...)```. The parameter parm can be assigned with numbers (columns of the model data.frame) or names like: 'y', 'x', 'z'.
*```deviance()``` It returns the deviance of a fitted blm model object.
*```fitted()``` Returns the fitted values extracted from the object model of class blm.
*```plot()``` Returns 4 grid arranged plots of the blm model object. The currently available plots are: 'Residuals vs Fitted values', 'Normal Q-Q plot' of standardized residuals', 'Regression Model' a plot of the first predictor and its response and a 'Histogram of Residuals' to observe the normality of the distribution.
*```predict()``` If additional data is provided, it gives the predicted values by evaluating the regression function. Otherwise, it gives the predictions based on the data used to fit the model.
*```print()``` It prints the called function and the coefficients of a blm model object.
*```residuals()``` It returns the model residuals (observed - predicted) from a blm object.
*```summary()``` Returns a summary.blm object, which contains summary statistics and the following attributes: "data", "sys", "residuals", "coefficients", "significance", "SS_total", "SS_residuals", "R_squared".

## Example

```{R, message=FALSE, warning =FALSE}
library(datasets)
data("iris")
attach(iris)
library(blm)

# There is a high correlation between Petal Lenght and Sepal Length
cor(iris$Petal.Length, iris$Sepal.Length)

# Visualizing it
plot(Sepal.Length, Petal.Length, col=c("red", "green", "blue")[Species], pch=(15:17)[Species], main="Edgar Anderson's Iris Dataset", ylab = 'Petal Length (cm)', xlab = 'Sepal Length (cm)')
legend("topleft", legend=c(levels(iris$Species)), col=c("red", "green", "blue"), pch=c(15:17, -1, -1), lty=c(-1, -1, -1))

# We can model the relationship between Petal length and Sepal length
reg = blm(Petal.Length ~ Sepal.Length, alpha = 1, beta = 1.3)
class(reg)
print(reg)
(coef_reg = coefficients(reg))

summ_reg = summary(reg)
attributes(summ_reg)

slope = coef_reg[2,1]
intercept = coef_reg[1,1]

# Plotting
plot(reg)

# Prediction of Petal Length given a new data
new_Sepal = data.frame(Sepal.Length = runif(100, min(Sepal.Length), max(Sepal.Length)))

predict_Plength = predict(reg, new_Sepal)
head(predict_Plength)
```

## Author(s)

This package was created for the course 'Data Analysis and Software Development' held at Aarhus University under the guidance of Professor [Thomas Mailund](http://www.mailund.dk/index.php/about/).

## References
Introduction to Data Science and Statistical Programming in R (Thomas Mailund).