---
title: "Statistics"
author: "Maria Izabel"
date: "January 3, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Bayesian linear regresssion (blm)

```blm``` is a R package for fitting linear models in which the statistical analysis were undertaken within the context of Bayesian inference. The ingredients for a regression linear model include the response vector $y= (y_1, y_2, y_3, ..., y_n)$ and a $n$ x $p$ design matrix (e.g. composed of explanatory variables) $X = [x_1, x_2, ..., x_p]$. The linear regression model is composed by an intercept ($w_0$), a slope ($w_1 / \beta$) and the error term:

$y_i = w_0 + w_1^Tx_i + ε$, where $ε_i$ is $N(0,\sigma^2)$.

Once we have w, $\sigma^2$, the predictors and the response variable, the likelihood function can be calculated as follow:

$P(y_i |w, X, \sigma^2) = N(w^Tx_i, \sigma^2)$ 

Note that the $\sigma^2$ can be estimated as $1/\beta$ where $\beta$ is the precision parameter. In the Bayesian approach, one puts prior distributions on one or both $w$ and $\sigma^2$. It is obvious to see that as we increase our prior precision we decrease the prior variance and we place greater weight on the prior mean relative to the data. 

The peculiarities of the Bayesian model compared to the frequentist model is that allow us to give our assumptions, or prior beliefs, about unknown parameters by specifying the prior distribution over those parameters before seeing the data. The way we do it is by treating the weights (w) as random variables coming from a distribution we have partial knowlegde about ($p(w|\alpha) = N(0, \alpha^-1I)$). Once we observe the data we can compute the posterior probability distribution for the parameters, given the observed data ($p(w|x,y)$) and the hyperparameters $\alpha$ and $\beta$ $p(w|x,y, \alpha, \beta)$. 

With a bit of math and based on the assumption of conjugate distributions, the posterior distribution is also following a Gaussian normal distribution: $p(y\,|\,x,\mathbf{x},\mathbf{y},\alpha,\beta) = \mathrm{N}\left(\mathrm{m}(\mathbf{x},\mathbf{y})'\phi(x),\;\sigma^2(x;\mathbf{x},\mathbf{y})\right)$
where $\mathrm{m}(\mathbf{x},\mathbf{y})$ is the mean from the posterior distribution of $\mathbf{w}$ and where $\sigma^2(x;\mathbf{x},\mathbf{y})=1/\beta+\phi(x)'\mathbf{S}(\mathbf{x},\mathbf{y})\,\phi(x)$ where $\mathbf{S}(\mathbf{x},\mathbf{y})$ is the covariance matrix from the posterior distribution of $\mathbf{w}$.

The posterior distribution can be lately used to:

1. Make predictions for new data points (by integrating over the posterior distribution, see update.blm).
2. Account for uncertanty in the parameters values (see confint.blm)
 
The features of the package have some similarities to the [lm]{https://stat.ethz.ch/R-manual/R-devel/library/stats/html/lm.html} R package. 
The blm package is available through github, note that this source is under development (version 0.1.0).
